# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6e69d27fca21b52283a46c673621b82ba4a601e362cab380ca2c26b08261758f76bd7c468249fb955ad22ffa1aa2686c937a6184aeda1176ac953dfd30ba394d

test:
  secret_key_base: 3d980553e19e5ab305634d418e7f4da7f600aa134278bac5fc20ea430c0929a14f5b8b98ab30111f4242ce4d7a484c12abf3a18dbb36d3d01f13c3018f296c3b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
